name: Test
on:
  - push
  - pull_request
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Run test
        run: npm test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Run TypeScript Check
        run: npx tsc --noEmit
  deploy:
    name: Deploy
    needs: [test, lint]
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13.15.4
        with:
          args: deploy
        env:
          # Firebase secrets
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
          # Deployment environment secrets
          API_TOKEN: ${{secrets.API_TOKEN}}
          BLUESKY_PASSWORD: ${{secrets.BLUESKY_PASSWORD}}
          BLUESKY_USERNAME: ${{secrets.BLUESKY_USERNAME}}
          FIREBASE_GITHUB_TOKEN: ${{secrets.FIREBASE_GITHUB_TOKEN}}
          FITBIT_CLIENT_ID: ${{secrets.FITBIT_CLIENT_ID}}
          FITBIT_CLIENT_SECRET: ${{secrets.FITBIT_CLIENT_SECRET}}
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
          MASTODON_ACCESS_TOKEN: ${{secrets.MASTODON_ACCESS_TOKEN}}
          MASTODON_HOSTNAME: ${{secrets.MASTODON_HOSTNAME}}
          SCRAPBOX_SID: ${{secrets.SCRAPBOX_SID}}
          SLACK_CHANNELS_GENSHIN: ${{secrets.SLACK_CHANNELS_GENSHIN}}
          SLACK_SIGNING_SECRET: ${{secrets.SLACK_SIGNING_SECRET}}
          SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
          SLACK_TOKENS: ${{secrets.SLACK_TOKENS}}
          STATUSPAGE_COMPONENT_ID: ${{secrets.STATUSPAGE_COMPONENT_ID}}
          STATUSPAGE_PAGE_ID: ${{secrets.STATUSPAGE_PAGE_ID}}
          STATUSPAGE_TOKEN: ${{secrets.STATUSPAGE_TOKEN}}
          THREADS_PASSWORD: ${{secrets.THREADS_PASSWORD}}
          THREADS_POST_URL: ${{secrets.THREADS_POST_URL}}
          THREADS_USERNAME: ${{secrets.THREADS_USERNAME}}
          THREADS_USER_AGENT: ${{secrets.THREADS_USER_AGENT}}
          THREADS_USER_ID: ${{secrets.THREADS_USER_ID}}
          URLS_TWEETS_JSON: ${{secrets.URLS_TWEETS_JSON}}
